//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colosoft.Presentation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Colosoft.Presentation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot register a CompositeCommand in itself..
        /// </summary>
        internal static string CannotRegisterCompositeCommandInItself {
            get {
                return ResourceManager.GetString("CannotRegisterCompositeCommandInItself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot register the same command twice in the same CompositeCommand..
        /// </summary>
        internal static string CannotRegisterSameCommandTwice {
            get {
                return ResourceManager.GetString("CannotRegisterSameCommandTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection accepts only objects of type InputGesture..
        /// </summary>
        internal static string CollectionOnlyAcceptsInputGestures {
            get {
                return ResourceManager.GetString("CollectionOnlyAcceptsInputGestures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neither the executeMethod nor the canExecuteMethod delegates can be null..
        /// </summary>
        internal static string DelegateCommandDelegatesCannotBeNull {
            get {
                return ResourceManager.GetString("DelegateCommandDelegatesCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T for DelegateCommand&amp;lt;T&amp;gt; is not an object nor Nullable..
        /// </summary>
        internal static string DelegateCommandInvalidGenericPayloadType {
            get {
                return ResourceManager.GetString("DelegateCommandInvalidGenericPayloadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O esquema do caminho inválido..
        /// </summary>
        internal static string MenuItem_InvalidPathScheme {
            get {
                return ResourceManager.GetString("MenuItem_InvalidPathScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe uma instancia aberta. Feche ela ante de executar essa operação..
        /// </summary>
        internal static string MenuItemsInserter_InvalidOperation_ThereIsOpenInstance {
            get {
                return ResourceManager.GetString("MenuItemsInserter_InvalidOperation_ThereIsOpenInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation not supported on a read-only InputGestureCollection..
        /// </summary>
        internal static string ReadOnlyInputGesturesCollection {
            get {
                return ResourceManager.GetString("ReadOnlyInputGesturesCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every RoutedEventArgs must have a non-null RoutedEvent associated with it..
        /// </summary>
        internal static string RoutedEventArgsMustHaveRoutedEvent {
            get {
                return ResourceManager.GetString("RoutedEventArgsMustHaveRoutedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change the RoutedEvent property while the RoutedEvent is being routed..
        /// </summary>
        internal static string RoutedEventCannotChangeWhileRouting {
            get {
                return ResourceManager.GetString("RoutedEventCannotChangeWhileRouting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataTemplateSelector &apos;{0}&apos; not found..
        /// </summary>
        internal static string ThemeManager_DataTemplateSelectorNotFound {
            get {
                return ResourceManager.GetString("ThemeManager_DataTemplateSelectorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default theme not found..
        /// </summary>
        internal static string ThemeManager_DefaultThemeNotFound {
            get {
                return ResourceManager.GetString("ThemeManager_DefaultThemeNotFound", resourceCulture);
            }
        }
    }
}
